### ISSUE TITLE
[회원가입]  회원가입 API 수정 및 추가

### ISSUE THREAD

**Issue by highright96** [bookwhale/bookwhale-server#55]
## Task
- [ ] 아이디
    - [ ] 중복확인
- [ ] 비밀번호
    - [ ] 영어 소문자, 숫자. 특수문자 포함 8자리 이상 
- [ ] 이름
- [ ] 이메일
    - [ ] 이메일 인증 (Redis 활용)
        - [ ] 인증코드 생성
        - [ ] 인증코드 확인
- [x] 닉네임 자동 생성( 예시. 지나가는나그네1)

**Comment by GentleDot** [comment]
회원가입 -> OAuth 인증 방식 변경으로 close 해두겠습니다.
